[package]
name = "nm_launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.30"
